// src/config/appwrite.js

export const DATABASE_ID = import.meta.env.VITE_APPWRITE_DATABASE_ID;

export const RESOURCES_COLLECTION_ID = import.meta.env
  .VITE_APPWRITE_RESOURCES_COLLECTION_ID;

export const ACTIVITIES_COLLECTION_ID = import.meta.env
  .VITE_APPWRITE_ACTIVITIES_COLLECTION_ID;

export const STORAGE_BUCKET_ID = import.meta.env
  .VITE_APPWRITE_STORAGE_BUCKET_ID;

export const USERS_COLLECTION_ID = import.meta.env
  .VITE_APPWRITE_USERS_COLLECTION_ID;

export const PYQS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_PYQS_COLLECTION_ID;

export const SYLLABUS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_SYLLABUS_COLLECTION_ID;

export const UNITS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_UNITS_COLLECTION_ID;

export const PROGRAMS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_PROGRAMS_COLLECTION_ID;

export const SUBJECTS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_SUBJECTS_COLLECTION_ID;

export const CLASSES_COLLECTION_ID = import.meta.env.VITE_APPWRITE_CLASSES_COLLECTION_ID;

export const ENROLLMENTS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_ENROLLMENTS_COLLECTION_ID;

export const SESSIONS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_SESSIONS_COLLECTION_ID;

export const ATTENDANCE_RECORDS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_ATTENDANCE_RECORDS_COLLECTION_ID;

export const SESSION_TOKENS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_SESSION_TOKENS_COLLECTION_ID